label: Icons
status: wip
context:
  size: 2x
  semantic: true
  screenReader: Screen reader description
  icons:
    - name: pentagon
      description: pentagon
    - name: triangle
      description: triangle
    - name: leaf
      description: leaf
    - name: file
      description: file
    - name: star
      description: star
    - name: flag
      description: flag
    - name: reset
      description: reset
    - name: exclamation
      description: exclamation
    - name: exclamation-circle
      description: exclamation circle
    - name: question
      description: question
    - name: angle-left
      description: angle left
    - name: angle-right
      description: angle right
    - name: federal-building
      description: federal building
    - name: ellipsis
      description: ellipsis
    - name: arrow-up
      description: arrow up
    - name: arrow-down
      description: arrow down
    - name: arrow
      description: arrow
    - name: thumb-up
      description: thumb up
    - name: thumb-down
      description: thumb down
    - name: download
      description: download
    - name: upload
      description: upload
    - name: log-out
      description: log out
    - name: log-in
      description: log in
    - name: users
      description: users
    - name: user
      description: user
    - name: user-circle
      description: user circle
    - name: search
      description: search
    - name: search-circle
      description: search circle
    - name: question-circle
      description: question circle
    - name: video-square
      description: video square
    - name: video-circle
      description: video circle
    - name: video-play
      description: video play
    - name: alert-warning
      description: alert warning
    - name: check-circle
      description: check circle
    - name: check
      description: check
    - name: information-circle
      description: information circle
    - name: alert-info
      description: alert info
    - name: alert-error
      description: alert error
    - name: bars
      description: bars
    - name: bell
      description: bell
    - name: book
      description: book
    - name: bookmark
      description: bookmark
    - name: calendar
      description: calendar
    - name: calendar-add
      description: calendar add
    - name: calendar-check
      description: calendar check
    - name: envelope
      description: envelope
    - name: file-chart-line
      description: file-chart-line
    - name: filter
      description: filter
    - name: home
      description: home
    - name: invoice
      description: invoice
    - name: receipt
      description: receipt
    - name: link
      description: link
    - name: unlink
      description: unlink
    - name: new-note
      description: new-note
    - name: print
      description: print
    - name: ruler-pencil
      description: ruler-pencil
    - name: share
      description: share
    - name: trash
      description: trash
    - name: workspace
      description: workspace
    - name: ship
      description: ship
    - name: folder
      description: folder
    - name: folder-alt-1
      description: folder alt 1
    - name: folder-alt-2
      description: folder alt 2
    - name: open-doors
      description: open doors
    - name: building
      description: building
    - name: building-alt
      description: building alt
    - name: pen-paper
      description: pen and paper
    - name: tag
      description: tag
    - name: photo
      description: photo
    - name: photo-alt
      description: photo alt
    - name: new-version
      description: new version
    - name: article
      description: article
    - name: note
      description: note
    - name: request
      description: request
    - name: messages
      description: messages
    - name: comment
      description: comment
    - name: mobile
      description: mobile
    - name: tablet
      description: tablet
    - name: document
      description: document
    - name: document-add
      description: document add
    - name: document-search
      description: document search
    - name: document-pdf
      description: document pdf
    - name: add
      description: add
    - name: exit
      description: exit
    - name: angle-circle
      description: angle circle
    - name: add-req
      description: add request
    - name: attachment
      description: attachment
