label: Cards
status: wip
preview: "@sam-content"
variants:
  - name: default
    label: SDS Card
    context:
      label:
        classes: "sds-card"

  - name: default
    label: SDS Header Card
    context:
      label:
        classes: "sds-card sds-card__header"

  - name: Alternative
    label: SDS Vertical Card
    context:
      label:
        classes: "sds-card sds-card--vertical"

  - name: Alternative
    label: SDS Tile Card
    context:
      label:
        classes: "sds-card sds-card--tile"
