label: Side navigation
status: ready
# preview: '@uswds-framed'

context:
  sidenav:
    links: &default_links
      - text: Parent link
      - text: Current page
        current: true
        links:
          - text: Child link
          - text: Child link
            current: true
            links:
              - text: Grandchild link
              - text: Grandchild link
              - text: Grandchild link
                current: true
              - text: Grandchild link
          - text: Child link
          - text: Child link
          - text: Child link
      - text: Parent link
  sidenav:
    links: &compare_links
      - text: Parent link
      - text: Current page
        current: true
        links:
          - text: Child link
          - text: Child link
            current: true
            links:
              - text: Grandchild link
              - text: Grandchild link
              - text: Grandchild link
                current: true
              - text: Grandchild link
          - text: Child link
          - text: Child link
          - text: Child link
      - text: Parent link

variants:
  - name: default

  - name: compare
  