name: pages
status: wip
preview: "@sam-content"
default: landing-page
variants:
  - name: landing-page
    notes: "Landing Page"
    context:
      tileIcon:
        type: stack
        icons:
          - icon: triangle
            classes: fa-stack-2x text-accent-cool-light fa-1x
          - icon: video-circle
            classes: fa-stack-1x text-base fa-2x
      iconSize: lg
      cards:
      - title: Data Services
        contents:
          - listTitle: APIs
            list:
              modifiers:
                - icon
                - unstyled
              items:
                - link:
                    text: Getting Started with web services
                    href: ' '
                  icon:
                    icon: note
                    classes: fa-lg fa-fw
                - link:
                    text: Go to entity registration API
                    href: ' '
                  icon:
                    icon: angle-right
                    classes: fa-lg fa-fw
                - link:
                    text: Go to exclusions API
                    href: ' '
                  icon:
                    icon: angle-right
                    classes: fa-lg fa-fw
          - listTitle: Connect to Service APIs
            list:
              modifiers:
                - icon
                - unstyled
              items:
                - link:
                    text: Downloading entity registration files
                    href: ' '
                  icon:
                    icon: note
                    classes: fa-lg fa-fw
                - link:
                    text: Downloading exclusion files
                    href: ' '
                  icon:
                    icon: note
                    classes: fa-lg fa-fw
                - link:
                    text: Go to entity registration downloads
                    href: ' '
                  icon:
                    icon: angle-right
                    classes: fa-lg fa-fw
                - link:
                    text: Go to exclusions downloads
                    href: ' '
                  icon:
                    icon: angle-right
                    classes: fa-lg fa-fw
      - title: More about Entity Information
        secondCard: true
        contents:
          - listTitle: Exclusion Resources
            list:
              modifiers:
                - icon
                - unstyled
              items:
                - link:
                    text: Types of exclusions
                    href: ' '
                  icon:
                    icon: note
                    classes: fa-fw fa-lg
                - link:
                    text: Legacy CT Codes
                    href: ' '
                  icon:
                    icon: note
                    classes: fa-fw fa-lg
                - link:
                    text: Agency Exclusion POCs
                    href: ' '
                  icon:
                    icon: note
                    classes: fa-fw fa-lg
          - listTitle: User Guides
            list:
              modifiers:
                - icon
                - unstyled
              items:
                - link:
                    text: Exclusions Managmement User Guide for Federal Users
                    href: ' '
                  icon:
                    icon: note
                    classes: fa-fw fa-lg
                - link:
                    text: Data Services User Guide
                    href: ' '
                  icon:
                    icon: note
                    classes: fa-fw fa-lg
          - listTitle: Help
            list:
              modifiers:
                - icon
                - unstyled
              items:
                - link:
                    text: Frequently Asked Questions
                    href: ' '
                  icon:
                    icon: question
                    classes: fa-fw fa-lg
                - link:
                    text: Glossary Terms
                    href: ' '
                  icon:
                    icon: book
                    classes: fa-fw fa-lg
                - link:
                    text: Videos
                    href: ' '
                  icon:
                    icon: video-square
                    classes: fa-fw fa-lg
  - name: help-results
    label: Help Results
    context:
      list:
          items:
            - text: The Integrated Award Environment Digest 2019
            - text: Offering the ability to search data by number, keyword, or location for exact and immediate results
            - text: Providing easy to use search filters to quickly find the right wage determination
      menu:
        items:
          - text: Related Articles
          - link:
              text: As a federal Hierarchy Administrator, what data is needed to create an office?
              href: ' '
          - link:
              text: Wage Determination Now in beta.SAM.gov
              href: ' '
          - link:
              text: Assistance Admin Transition
              href: ' '
          - link:
              text: Non-Standard Wage
              href: ' '
  - name: page-with-sidebar
    label: Page With Sidebar
    context:
        actionIcon:
          type: layers
          icons:
              -   icon: circle
                  prefix: fas
              -   icon: ellipsis
                  dataTransform: shrink-6
