name: Pages
status: wip
preview: "@sam-content"
default: full-page
variants:
  - name: full-page
    label: Full Page
    context:
      list:
        items:
          - text: The name of the domain from which you access the Internet, i.e. DHS.gov if you are connecting from a Department of Homeland Security domain or GMU.edu if you are connecting from George Mason University's domain
          - text: The date and time of your visit
          - text: The type and version of your Internet browser
          - text: The operating system of the machine running the Internet browser
          - text: The Internet address of the website you came from if it linked you directly to this site
          - text: The technical status of the request you made, i.e. was it successful or was there an error?
  - name: three-columns
    label: Three Columns
    context:
      base: sds-card
      title: Contract Opportunities
      colors:
        - title: Accent Cool
      header:
        style: left
      body: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed augue lacus viverra vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed augue lacus viverra vitae.

  - name: left-aside
    label: Left Aside

  - name: right-aside
    label: Right Aside

  - name: landing-page
    label: Landing Page
    context:
      iconSize: lg
      cards:
        - title: Data Services
          contents:
            - listTitle: APIs
              list:
                modifiers: ['unstyled', 'flex']
                items:
                  - text: Getting Started with web services
                    icon:
                      icon: note
                      classes: fa-lg fa-fw
                  - text: Go to entity registration API
                    icon:
                      icon: angle-right
                      classes: fa-lg fa-fw
                  - text: Go to exclusions API
                    icon:
                      icon: angle-right
                      classes: fa-lg fa-fw
            - listTitle: Connect to Service APIs
              list:
                modifiers: ['unstyled', 'flex']
                items:
                  - text: Downloading entity registration files
                    icon:
                      icon: note
                      classes: fa-lg fa-fw
                  - text: Downloading exclusion files
                    icon:
                      icon: note
                      classes: fa-lg fa-fw
                  - text: Go to entity registration downloads
                    icon:
                      icon: angle-right
                      classes: fa-lg fa-fw
                  - text: Go to exclusions downloads
                    icon:
                      icon: angle-right
                      classes: fa-lg fa-fw
        - title: More about Entity Information
          secondCard: true
          contents:
            - listTitle: Exclusion Resources
              list:
                modifiers: ['unstyled', 'flex']
                items:
                  - text: Types of exclusions
                    icon:
                      icon: note
                      classes: fa-fw fa-lg
                  - text: Legacy CT Codes
                    icon:
                      icon: note
                      classes: fa-fw fa-lg
                  - text: Agency Exclusion POCs
                    icon:
                      icon: note
                      classes: fa-fw fa-lg
            - listTitle: User Guides
              list:
                modifiers: ['unstyled', 'flex']
                items:
                  - text: Exclusions Managmement User Guide for Federal Users
                    icon:
                      icon: note
                      classes: fa-fw fa-lg
                  - text: Data Services ser Guide
                    icon:
                      icon: note
                      classes: fa-fw fa-lg
            - listTitle: Help
              list:
                modifiers: ['unstyled', 'flex']
                items:
                  - text: Frequently Asked Questions
                    icon:
                      icon: question
                      classes: fa-fw fa-lg
                  - text: Glossary Terms
                    icon:
                      icon: book
                      classes: fa-fw fa-lg
                  - text: Videos
                    icon:
                      icon: video-square
                      classes: fa-fw fa-lg

