name: pages
status: wip
preview: "@sam-content"
default: landing-page
variants:
  - name: landing-page
    notes: "Landing Page"
    context:
      iconSize: lg
      cards:
        - title: Data Services
          col: 5
          modifiers:
            - height-full
          color: accent-cool
          body:
            content:
              - component: list
                context:
                  title:
                    content: APIs
                    tag: h3
                  modifiers:
                    - unstyled
                    - flex
                  items:
                    - text: Getting Started with web services
                      icon:
                        icon: note
                        classes: fa-lg fa-fw
                      href: ' '
                    - text: Go to entity registration API
                      icon:
                        icon: angle-right
                        classes: fa-lg fa-fw
                      href: ' '
                    - text: Go to exclusions API
                      icon:
                        icon: angle-right
                        classes: fa-lg fa-fw
                      href: ' '
              - component: list
                context:
                  title:
                    content: Connect to Service APIs
                    tag: h3
                  modifiers:
                    - unstyled
                    - flex
                  items:
                    - text: Downloading entity registration files
                      icon:
                        icon: note
                        classes: fa-lg fa-fw
                      href: ' '
                    - text: Downloading exclusion files
                      icon:
                        icon: note
                        classes: fa-lg fa-fw
                      href: ' '
                    - text: Go to entity registration downloads
                      icon:
                        icon: angle-right
                        classes: fa-lg fa-fw
                      href: ' '
                    - text: Go to exclusions downloads
                      icon:
                        icon: angle-right
                        classes: fa-lg fa-fw
                      href: ' '
        - title: More about Entity Information
          col: 7
          color: accent-cool
          modifiers:
            - height-full
          body:
            grid: true
            content:
              - component: list
                col: 6
                context:
                  title:
                    content: Exclusion Resources
                    tag: h3
                  modifiers:
                    - unstyled
                    - flex
                  items:
                    - text: Types of exclusions
                      href: ' '
                      icon:
                        icon: note
                        classes: fa-fw fa-lg
                    - text: Legacy CT Codes
                      href: ' '
                      icon:
                        icon: note
                        classes: fa-fw fa-lg
                    - text: Agency Exclusion POCs
                      href: ' '
                      icon:
                        icon: note
                        classes: fa-fw fa-lg
              - col: 6
                html: <div class="add-aspect-16x9 bg-base-light margin-y-1"></div>
              - component: list
                col: 6
                context:
                  title:
                    content: User Guides
                    tag: h3
                  modifiers:
                    - unstyled
                    - flex
                  items:
                    - text: Exclusions Managmement User Guide for Federal Users
                      href: ' '
                      icon:
                        icon: note
                        classes: fa-fw fa-lg
                    - text: Data Services User Guide
                      href: ' '
                      icon:
                        icon: note
                        classes: fa-fw fa-lg
              - component: list
                col: 12
                context:
                  title:
                    content: Help
                    tag: h3
                  modifiers:
                  - unstyled
                  - flex
                  items:
                    - text: Frequently Asked Questions
                      href: ' '
                      icon:
                        icon: question
                        classes: fa-fw fa-lg
                    - text: Glossary Terms
                      href: ' '
                      icon:
                        icon: book
                        classes: fa-fw fa-lg
                    - text: Videos
                      href: ' '
                      icon:
                        icon: video-square
                        classes: fa-fw fa-lg

  - name: help-results
    label: Help Results
    context:
      list:
          items:
            - text: The Integrated Award Environment Digest 2019
            - text: Offering the ability to search data by number, keyword, or location for exact and immediate results
            - text: Providing easy to use search filters to quickly find the right wage determination
      menu:
        items:
          - text: Related Articles
          - text: As a federal Hierarchy Administrator, what data is needed to create an office?
            href: ' '
          - text: Wage Determination Now in beta.SAM.gov
            href: ' '
          - text: Assistance Admin Transition
            href: ' '
          - text: Non-Standard Wage
            href: ' '
  - name: page-with-sidebar
    label: Page With Sidebar
