label: Heading
status: wip
preview: "@sam"
variants:
  - name: default
    label: Heading
    context:
      label:

  - name: light
    label: Heading Light
    context:
      label:

  - name: links
    label: Heading Links
    context:
      label:      