label: Paragraph
status: wip
preview: "@sam-content"
context: 
    items: 
      - name: paragraph
        label: Paragraph
        weight: Regular
        size: 1 rem
        lheight: 1.25 rem
        color: Base-Dark (#454540)
      - name: large-paragraph
        label: Large Paragraph
        class: p--large
        weight: Regular
        size: 1.13 rem
        lheight: 1.5 rem
        color: Base-Dark (#454540)
      - name: fineprint-paragraph
        label: Fine Print Paragraph
        class: p--fine-print
        weight: Regular
        size: 0.87 rem
        lheight: 1 rem
        color: Base-Dark (#454540)
      - name: italic-paragraph
        label: Italic Paragraph
        class: p--italic
        weight: Regular
        size: 1 rem
        lheight: 1.25 rem
        color: Base-Dark (#454540)
      - name: semibold-paragraph
        label: Semibold Paragraph
        class: p--semibold
        weight: Semibold
        size: 1 rem
        lheight: 1.25 rem
        color: Base-Dark (#454540)
      - name: bold-paragraph
        label: Bold Paragraph
        class: p--bold
        weight: Bold
        size: 1 rem
        lheight: 1.25 rem
        color: Base-Dark (#454540)
      - name: bold-color-paragraph
        label: Bold Paragraph
        class: p--bold p--ink
        weight: Bold
        size: 1 rem
        lheight: 1.25 rem
        color: Base-Dark (#2e2e2a)
  