label: Buttons
status: ready
order: 3
preview: "@sam-content"
default: "primary"
variants:
  - name: secondary
    context:
      category: alternate
      label: Secondary buttons
      classes: 'usa-button--secondary'

  - name: tertiary
    context:
      category: alternate
      label: Tertiary buttons
      classes: 'usa-button--tertiary'

  - name: base
    context:
      category: alternate
      label: Gray buttons
      classes: 'usa-button--base'

  - name: outline
    context:
      category: outline
      label: outline buttons
      classes: 'usa-button--outline'

  - name: outline-inverse
    context:
      category: outline-inverse
      label: outline inverse buttons
      classes: 'usa-button--outline usa-button--inverse'

  - name: big
    context:
      category: 'big'
      label: Big button
      classes: 'usa-button--big'
