label: Buttons
status: wip
context:
  results: 3
  classes: 'button'
  scss: 'sam-styles/button'

variants:
  - name: default
    label: Default
  - name: clear
    context:
      category: alternate
      label: Gray buttons
      classes: 'button height-5'
      close: true
