label: Header
status: wip

variants:
  - name: default
    label: Compare
    status: null

  - name: extended
    label: Extended header
    context:
      header:
        primary:
          search: false
          id_prefix: extended-
          links:
            - text: Search
              href: ''
              id: nav-section-search
              links: false
            - text: Contracting
              id: nav-section-contracting
              links: false
            - text: Federal Assistance
              id: nav-section-federal-assistance
              links: false
            - text: Help
              href: ''
              id: nav-section-help
        secondary:
          search: false
          links:
            - text: Request
              icon: edit
            - text: Messages
              icon: comment
              notification: true
            - text: Workspace
              icon: th
            - text: Sign Out
              icon: sign-out-alt

  - name: extended-mega
    label: Extended with mega-menu
    context:
      header:
        primary:
          search: false
          id_prefix: extended-mega-
          mega: true
        secondary:
          search: true
