cd label: Header
status: wip

variants:
  - name: default
    label: Compare
    status: null

  - name: extended
    label: Extended header
    context:
      header:
        primary:
          search: false
          id_prefix: extended-
          links:
            - text: Section 1
              href: ''
              is_current: false
              id: nav-section-home
              links: false
            - text: Section 2
              is_current: false
              id: nav-section-one
              links: &subnav_links
                - text: Page title
                  href: '#'
                - text: Page title
                  href: '#'
                - text: A very long page title that goes onto two lines
                  href: '#'
            - text: Section 3
              id: nav-section-two
              links: *subnav_links
            - text: Section 4
              href: ''
            - text: Section 5
              href: ''
        secondary:
          search: false
          links:
            - text: Request
              icon: edit
            - text: Messages
              icon: comment
              notification: true
            - text: Workspace
              icon: th
            - text: Sign Out
              icon: sign-out-alt

  - name: extended-mega
    label: Extended with mega-menu
    context:
      header:
        primary:
          search: false
          id_prefix: extended-mega-
          mega: true
        secondary:
          search: true
