cd label: Header
status: wip

variants:
  - name: default
    label: Compare
    status: null

  - name: extended
    label: Extended header
    context:
      header:
        primary:
          search: false
          id_prefix: extended-
          links:
            - text: Search
              href: ''
              is_current: false
              id: nav-section-home
              links: false
            - text: Databank
              links: false
              is_current: false
              id: nav-section-one
            - text: Data Services
              id: nav-section-two
              links: false
            - text: Help
              href: ''
        secondary:
          search: false
          links:
            - text: Request
              sdsIcon: true
              icon: request
            - text: Messages
              sdsIcon: true
              icon: messages
            - text: Workspace
              sdsIcon: true
              icon: workspace
            - text: Sign Out
              sdsIcon: true
              icon: 'log-out'

  - name: extended-mega
    label: Extended with mega-menu
    context:
      header:
        primary:
          search: false
          id_prefix: extended-mega-
          mega: true
        secondary:
          search: true
