label: Alerts
status: wip
preview: "@sam-grid"
collated: true
variants:
  - name: default
    label: Default
    context:
      label:
        classes: "usa-alert"
      icon:
        icon: exclamation
        prefix: fa-2x
        buttons:
        - classes: accordion simple-toggle
          modifiers:
            - primary-lighter
          custom: aria-controls="alert-info-extension"
          icon:
            icon: caret-down
            prefix: fa
            classes:
            title: false
