preview: "@sam-content"
label: Demo
status: wip
default: bordered and shadowed
notes: |
  A horizontal header may have a title and a button.
  ___
  **Variables:**
  - color (*optional*): option of base, accent-cool, accent-warm, or feature
  - title
  - modifiers: [shadowed, bordered, vertical, and/or list]
  - header: *(false if no header)*
    - style: option of left, stacked, center, action or flex
    - link: url
    - icon: @icon
    - buttons: [@button]
    - action: Boolean
  - body
    - content
    - lists: [@list]
display:
  text-align: center
meta:
  colors:
    - title: Plain
    - modifier: base
      title: Base
    - modifier: accent-cool
      title: Accent Cool
    - modifier: accent-warm
      title: Accent Warm
    - modifier: feature
      title: Feature (Secondary)
context:
  card:
    color: null
    title: Contract Opportunities
    header:
      style: left
    modifiers:
      - shadowed
      - bordered
    body:
      content: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed augue lacus viverra vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed augue lacus viverra vitae.
variants:
  - name: bordered
    label: Bordered No Shadow
    context:
      card:
        modifiers:
          - bordered
  - name: shadowed
    label: Shadowed No Border
    context:
      card:
        modifiers:
          - shadowed
  - name: no shadow
    label: No Shadow or Border
    context:
      card:
        modifiers:
  - name: no header
    label: No Header
    notes: "508: card must have `aria-labelledby` attribute with a corresponding header outside of card"
    meta:
      colors:
    context:
      card:
        header: false
  - name: link header
    label: Link Header
    notes: Header can be a link.
    context:
      card:
        header:
          link: " "
  - name: header icon left
    label: Header Icon Left
    context:
      card:
        header:
          icon:
            icon: book
            classes: fa-2x fa-fw
  - name: header icon stacked
    label: Header Icon Stacked
    context:
      card:
        header:
          icon:
            icon: book
            classes: fa-2x
          style: stacked
  - name: header icon centered
    label: Header Icon Centered
    context:
      card:
        header:
          icon:
            icon: book
            classes: fa-2x fa-fw
          style: center
  - name: header button
    label: Header with One Button
    notes: A horizontal card header may have a title and a button.
    context:
      card:
        header:
          buttons:
            - modifiers:
              - outline
          style: flex
  - name: header buttons
    label: Header with Two Buttons
    notes: A horizontal card header may have a title and two buttons.
    context:
      card:
        header:
          buttons:
            - modifiers:
              - outline
            - modifiers:
              - outline
          style: flex
  - name: header action
    label: Header with Action Button
    notes: A horizontal card header may have an action button. Card headers with actions should have an action modifier "sds-card__header--action"
    context:
      card:
        header:
          action: true
          style: action
  - name: vertical
    label: Vertical Header
    notes: A card can have a vertical header
    context:
      card:
        modifiers:
          - shadowed
          - bordered
          - vertical
        header:
          icon:
            icon: question-circle
            classes: fa-2x
  - name: list
    label: List
    notes: Card layouts can be used for lists. Don't add bordered modifier to card -- just add to list
    context:
      card:
        modifiers:
          - shadowed
          - list
        body:
          lists:
            - modifiers:
              - bordered
              - unstyled
          content:
