title: Actions Menu
status: wip
preview: "@sam-content"
context:
    style: primary
    label: action
    icon:
        icon: ellipsis
        classes: fa-fw
        dataTransform: grow-5
    layeredIcon:
        type: layers
        icons:
            -   icon: circle
                prefix: fas
            -   icon: ellipsis
                dataTransform: shrink-6
