title: Actions Menu
status: wip
preview: "@sam"
context:
    style: primary
    label: action
    icon:
        icon: ellipsis
        classes: fa-fw
        dataTransform: grow-5
    layeredIcon:
        type: layers
        classes:  padding-left-4
        size: fa-1x
        icons:
            -   icon: circle
                size: fa-1x
                prefix: fas
                classes: text-primary
                dataTransform: grow-8
            -   icon: ellipsis
                prefix: sds
                dataTransform: shrink-1
                size: fa-1x
    layeredIcon2:
        type: layers
        classes:  padding-left-4
        size: fa-1x
        icons:
            -   icon: circle
                prefix: fas
                classes: text-primary
                dataTransform: grow-12
            -   icon: ellipsis
                prefix: sds
