label: Modal
status: wip
preview: "@sam-content"
context: 
    items: 
      - name: in-button-txt
        label: In-Button Text
        class: in-button-text
        weight: Bold
        size: 1.06 rem
        lheight: 1.5 rem
        color: Placeholder (#3F57A6)
      - name: under-button-txt
        label: Under-Button Text
        class: under-button-text
        weight: Regular
        size: 0.87 rem
        lheight: 1.0 rem
        color: Placeholder (#3F57A6)
      - name: modal-heading
        label: Modal Heading
        class: modal-heading
        weight: Semi-Bold
        size: 1.46 rem
        lheight: 2.0 rem
        color: Base-Dark (#454540)
      - name: modal-text
        label: Modal Text
        class: modal-text
        weight: Semi-Bold
        size: 1.13 rem
        lheight: 1.5 rem
        color: Base-Dark (#454540)
      - name: helper-text
        label: Helper Text
        class: helper-text
        weight: Regular
        size: 1.06 rem
        lheight: 1.25 rem
        color: Base (#757575)        
      - name: tag-label
        label: Tag Label
        class: tag-label
        weight: Bold
        size: 1.13 rem
        lheight: 1.25 rem
        color: Base-Dark (#454540)