label: Header
status: wip

variants:
  - name: default
    label: Compare
    status: null

  - name: extended
    label: Extended header
    context:
      header:
        primary:
          search: false
          id_prefix: extended-
        secondary:
          search: true

  - name: extended-mega
    label: Extended with mega-menu
    context:
      header:
        primary:
          search: false
          id_prefix: extended-mega-
          mega: true
        secondary:
          search: true
