label: Labels
status: wip
preview: "@sam-content"
variants:
  - name: default
    label: Info
    context:
      label:
        classes: "usa-tag"

  - name: chip
    label: Chip
    context:
      label:
        classes: "sds-tag sds-tag--chip"

  - name: outline
    label: Outline
    context:
      label:
        classes: "sds-tag sds-tag--outline"
