label: Large Alerts
status: wip
preview: "@sam-content"
context: 
    items: 
      - name: global-title
        label: Global Title
        class: global-title
        weight: Semi-Bold
        size: 1.13 rem
        lheight: 1.5 rem
        color: Base-Dark (#454540)
      - name: global-text
        label: Global Text
        class: global-text
        weight: Regular
        size: 1.13 rem
        lheight: 1.5 rem
        color: Base-Dark (#454540)
      - name: global-text-link
        label: Global Text Link
        class: global-text usa-link
        weight: Bold
        size: 1.13 rem
        lheight: 1.5 rem
        color: PLACEHOLDER (#3F57A6)      
      - name: page-title
        label: Page Title
        class: page-title
        weight: Semi-Bold
        size: 1.13 rem
        lheight: 1.5 rem
        color: Base-Dark (#454540)
      - name: page-text
        label: Page Text
        class: page-text
        weight: Regular
        size: 1.13 rem
        lheight: 1.5 rem
        color: Base-Dark (#454540)
      - name: page-text-link
        label: Page Text Link
        class: global-text usa-link
        weight: Bold
        size: 1.13 rem
        lheight: 1.5 rem
        color: PLACEHOLDER (#3F57A6)