label: Labels
order: 4
status: wip
preview: "@sam-content"
variants:
  - name: default
    label: Info
    context:
      label:
        classes: "usa-tag"

  - name: big
    label: Big
    context:
      label:
        classes: "usa-tag usa-tag-big"

  - name: chip
    label: Chip
    context:
      label: 
        classes: "sam label"
