label: Homepage
status: wip
preview: "@sam-content"
variants:
  - name: tag
    label: SDS Offical Tag
    context:
      label:
        classes: "sds-official-tag"

  - name: tile
    label: SDS Tile
    context:
      label:
        classes: "sds-tile"
