label: Buttons
status: ready
preview: "@sam-content"
default: "primary"
notes: ".usa-button--hover and .usa-button--active classes are just to show their formatting in this context but should not be used in production"
context:
  text: Button
  states:
    - hover
    - active
    - focus
    - disabled
  mocos:
    - buttons: 
      - name: default
        text: Defualt

      - name: disabled
        text: Disabled
        disabled: true

    - buttons:
      - name: secondary
        text: Secondary
        modifiers: 
          - 'secondary'

      - name: danger
        text: Danger
        modifiers: 
          - 'danger'

      - name: base
        text: Base
        modifiers: 
          - 'base'

      - name: outline
        category: outline
        text: Outline
        modifiers: 
          - 'outline'

      - name: outline-inverse
        category: outline-inverse
        text: Outline inverse
        modifiers: 
          - 'outline'
          - 'inverse'


variants:
  - name: secondary
    context:
      category: alternate
      label: Secondary buttons
      classes: 'usa-button--secondary'

  - name: danger
    context:
      category: alternate
      label: Danger buttons
      classes: 'usa-button--danger'

  - name: base
    context:
      category: alternate
      label: Gray buttons
      classes: 'usa-button--base'

  - name: outline
    context:
      category: outline
      label: Outline buttons
      classes: 'usa-button--outline'

  - name: outline-inverse
    context:
      category: outline-inverse
      label: Outline inverse buttons
      classes: 'usa-button--outline usa-button--inverse'

  - name: icon
    label: Icon
    context:
      label:
        classes: "sds-button--icon"
