label: Buttons
status: ready
preview: "@sam-content"
default: "primary"
context:
  text: Button
variants:
  - name: secondary
    context:
      category: alternate
      label: Secondary buttons
      classes: 'usa-button--secondary'

  - name: danger
    context:
      category: alternate
      label: Danger buttons
      classes: 'usa-button--danger'

  - name: base
    context:
      category: alternate
      label: Gray buttons
      classes: 'usa-button--base'

  - name: outline
    context:
      category: outline
      label: Outline buttons
      classes: 'usa-button--outline'

  - name: outline-inverse
    context:
      category: outline-inverse
      label: Outline inverse buttons
      classes: 'usa-button--outline usa-button--inverse'

  - name: icon
    label: Icon
    context:
      label:
        classes: "sds-button--icon"
      buttons:
        - icons:
            type: stack
            size: 2x
            icons:
              - icon: triangle
                classes: fa-stack-2x text-accent-cool-light fa-1x
              - icon: folder
                classes: fa-stack-1x text-base fa-2x
        - icons:
            type: stack
            size: 2x
            icons:
              - icon: pentagon
                classes: fa-stack-2x text-accent-cool-light fa-1x
              - icon: check-circle
                classes: fa-stack-1x text-base fa-2x
