label: Data Entry Fields
status: wip
preview: "@sam-content"
context: 
    items: 
      - name: group-input-label
        label: Group Input Label
        class: input-label--group
        weight: Semi-Bold
        size: 1.0 rem
        lheight: 1.25 rem
        color: Ink (#2E2E2A)
      - name: input-label
        label: Input Label
        class: input-label
        weight: Regular
        size: 1.0 rem
        lheight: 1.25 rem
        color: Ink (#2E2E2A)
      - name: entered-text
        label: Entered Text
        class: entered-text
        weight: Regular
        size: 1.0 rem
        lheight: 1.25 rem
        color: Placeholder (#3D4551)
      - name: field-paragraph
        label: Field Paragraph
        class: field-paragraph
        weight: Regular
        size: 1.0 rem
        lheight: 1.25 rem
        color: Base-Dark (#454540) 